apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  template:
    spec:
      containers:
        - name: gateway
          imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  template:
    spec:
      containers:
        - name: orchestrator
          imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-coordinator
spec:
  template:
    spec:
      containers:
        - name: ml-coordinator
          imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-admin
spec:
  template:
    spec:
      containers:
        - name: ui-admin
          imagePullPolicy: Never