scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: gateway
    static_configs:
      - targets: ['gateway:9095']
  - job_name: orchestrator
    static_configs:
      - targets: ['orchestrator:9100']